### ISSUE TITLE
How to set the API key programmatically when more than one auth schema type is used

### ISSUE THREAD

**Issue by xSAVIKx** [mrin9/RapiDoc#492] opened 2021-06-05 17:39 UTC
I've seen an example of setting the API key programmatically, but it looks like the `api-key-name` when set will not ever change. This is the first issue.

The second one is that it's not possible to set multiple API key names and values (or at least I have not found it).

E.g. Swagger UI supports this kind of authentication by exposing an API to set auth params with explicitly saying which auth params are being set (you can do this multiple times for different auth params).

The use case: the API is separated into several groups and each group requires a particular type of API key. So, if we use the same auth schema for all APIs at once, they all would be visually "enabled" even though the API key will not work for some. The idea is to have different API auth schemas and "enable" APIs based on the presence of the API key.

**Comment by mrin9** [comment] 2021-06-08 16:21
will look into it soon

**Comment by xSAVIKx** [comment] 2021-06-15 18:54
@mrin9 looks like this won't be available for at least a month while you're on the summer break, right? Maybe you can give some guidance on how you'd like to move with the feature?
Maybe I'd be able to create a PR then.

**Comment by mrin9** [comment] 2021-08-17 21:07
Thanks for offering a PR.

using the attribute `api-key-name` and other related ones are for those specs which do not define security options yet they still like to send some security headers. 
This approach shouldn't be the one for the specs which has complex security requirements

For working with multiple security schemes, it is preferred to use OpenAPI's security construct. 
That is
- first the spec must define all the security schemes
- and then map each endpoint with one or more security-schemes (can use `AND` and `OR` to define these combinations)

Here is an example of such a spec
https://mrin9.github.io/RapiDoc/examples/oauth-demo.html#auth

Once you have your spec defined properly, it will be structured like below, I think after this, its a matter of exposing the click event of `GET TOKEN` button as a method/interface 

![image](https://user-images.githubusercontent.com/5056899/129800331-81077e60-b827-4f04-9d2b-ff2b60ed48bf.png)


let me know if thats clear and will you be willing to work on that ?

**Comment by mrin9** [comment] 2021-09-13 20:49
It is in works. for an example checkout https://mrin9.github.io/RapiDoc/examples/auth.html#operations-top
you may test at your end or provide any feedback while we are developing it

**Comment by xSAVIKx** [comment] 2021-09-18 06:47
@mrin9 thx for the update!

I've tried to use it, but either I am doing smth wrong or smth is a bit wrong with the approach. At least it is not working for me.

So, a couple of things I've stumbled across while trying to make it work:
1) The doc says I need to use `setHttpUserNameAndPassword` if I want to work with HTTP bearer (cause it is a kind of HTTP auth), but in fact, I need to use `setApiKey("http-bearer", "jwtTokenValue")`.
![image](https://user-images.githubusercontent.com/5675689/133879026-43e7499f-8cb4-41f4-b335-c4589d2af4b9.png)

2) Even though the call is going inside, it seem the token value is not set into the request header. I wasn't able to debug it though.

Here's an example of the auth schema I used: 
```
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

And I set the JWT programmatically using:
```
docEl.setApiKey("Authorization", jwtToken);
```

**Comment by xSAVIKx** [comment] 2021-09-18 06:53
I've also tried using `setApiKey` with non-http auth schema, but it doesn't work for me either. At least the request sent in the end has no value in the `Authorization` header. But the UI is now updated properly (stating the API key is indeed updated).

**Comment by 0x78f1935** [comment] 2021-09-18 18:03
I think I might have encountered a bug and came out on this topic.
My spec looks like this:

```
self.API_SPEC_OPTIONS = {
    "components": {
        "securitySchemes": {
            "long-lived-oauth": {
                "type": "oauth2",
                "description": "Provides an OAuth token thats valid for long durations",
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": self.TOKEN_URL,
                        "scopes": self.SCOPES
                    },
                }
            },
            "bearer-token": {
                "type": "http",
                "description": "Use the Oauth token thats valid for long durations",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            },
            # "bearer-token": {
            #     "type": "apiKey",
            #     "in": "header",
            #     "api-key-name": "Authentication Bearer",
            #     "description": "Use the Oauth token thats valid for long durations"

            # },
        },
    },
    "security": [
        {
            "long-lived-oauth": [],
            "bearer-token": []
        }
    ]
}
```

- My `long-lived-oauth` flow works.
- When I decide to use the access token instead of client_id + client_secret (`bearer-token` flow) it seems like rapidoc doesn't send the bearer token set in the UI field within its request headers
![image](https://user-images.githubusercontent.com/14298262/133898142-fa037b9d-7fc5-4ca6-830b-37d70b2a5ff7.png)

The field that seems to be broken is this field
![image](https://user-images.githubusercontent.com/14298262/133898182-c775d34f-c488-46bf-a7ea-aeffe92a1e67.png)

I've validated my access_token and my request with postman and those seem to work fine,
Is there something I'm missing? Would like to work on a solution asap

**Comment by mrin9** [comment] 2021-09-19 02:02
Thanks for the detail analysis and screenshots - I was able to recreate this issue on my end and will provide a fix soon

**Comment by 0x78f1935** [comment] 2021-09-19 02:35
> Thanks for the detail analysis and screenshots - I was able to recreate this issue on my end and will provide a fix soon

Thank you very much for the fast response!

**Comment by mrin9** [comment] 2021-09-19 04:12
there is a `9.1.1-beta` which you can get from the `dist\rapidoc-min.js` folder https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js

this contains the latest fix for this issue. Can any of you confirm me if it takes care of your issues ?

we have a patch window opening tomorrow - and I would like to get this fixed released in `9.1.1`
Thanks for testing it out

**Comment by 0x78f1935** [comment] 2021-09-19 05:28
> there is a `9.1.1-beta` which you can get from the `dist\rapidoc-min.js` folder https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js

Hi, I've tried the url provided but it seems I'm unable to run this url with my setup. I get the following error in the console.
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

I'm running the standalone version of rapidoc

**Comment by mrin9** [comment] 2021-09-19 06:13
you should copy and save the content in `rapidoc-min.js` file and refer it locally in you script tag 
```html
<script type="module" src="local/path/for/rapidoc-min.js"></script>

```

**Comment by 0x78f1935** [comment] 2021-09-19 15:19
@mrin9 I have confirmed that the problem is resolved! 
Should I keep the file locally for production too? Seems logical.

Anyway, Thank you for the super fast fix! (sorry for my late response, I fel asleep ;p )

**Comment by mrin9** [comment] 2021-09-19 17:13
> Should I keep the file locally for production too? Seems logical.

Recommendation is, either to use the released version from CDN or use a local copy of released version.

We will be patching this soon in `9.1.1` which will be released anytime in next week, until then you may use it production but plan to update it soon with released version

**Closed** 2021-09-21 01:30 UTC
