### ISSUE TITLE
a.authorizationUrl is undefined with oAuth2 clientCredentials definition

### ISSUE THREAD

**Issue by W0nderMuffin** [mrin9/RapiDoc#675] opened 2022-02-24 13:32 UTC
System:
rapidoc `9.1.8`
latest firefox and chrome

## How it is:

We are using rapidoc in our vue component with allow-authentication set to true
```html
<rapi-doc
      ref="specRef"
      render-style="read"
      style="height: 100vh; width: 100%"
      allow-authentication="true"
      allow-try="true"
    ></rapi-doc>
```

with a swagger.json with the security scheme:
```json
        "securitySchemes": {
            "jwtToken": {
                "bearerFormat": "JWT",
                "description": "foo",
                "scheme": "bearer",
                "type": "http"
            },
            "oauth2client": {
                "description": "Client credential flow...",
                "flows": {
                    "clientCredentials": {
                        "scopes": {},
                        "tokenUrl": "https://some.url"
                    }
                },
                "type": "oauth2"
            }
        }
 ```

And in the browser we receive the error:
`TypeError
a.authorizationUrl is undefined`

## How to reproduce:

Code Sandbox Example:
https://codesandbox.io/s/charming-pine-doqy78

if you change the rapidoc version down to 9.1.4 it works again :)

**Comment by mrin9** [comment] 2022-02-24 13:54
duplicate of #667

**Closed by mrin9** 2022-02-24 13:54 UTC
