### ISSUE TITLE
ApiKey is prefixed with %20 in query

### ISSUE THREAD

**Issue by umeckel** [mrin9/RapiDoc#630] opened 2021-12-18 12:41 UTC
If i enter a api key as query parameter its always got prefixed with an %20.

Occurs in 
- 9.1.3,
- 9.1.2, 
- 9.1.1 and 
- 9.1.0 

but not in 9.0.0

**Comment by afranke** [comment] 2021-12-29 17:42
Already fixed in master, by 06137450de5014435e90cbe76d7f7f7a262668a6. Duplicate of #570

**Closed** 2022-01-11 15:51 UTC
