### ISSUE TITLE
Show HTTP method in the sidebar

### ISSUE THREAD

**Issue by kamaydeo** [mrin9/RapiDoc#237] opened 2020-06-17 03:24 UTC
It would nice to see the method name (GET/PUT/POST) before the operation in the sidebar. I'm not sure if it's configurable.

![image](https://user-images.githubusercontent.com/2191760/84851468-5cc7cd80-b028-11ea-8edc-31c81b1fcaf5.png)

Something like this -- 
![image](https://user-images.githubusercontent.com/2191760/84851509-779a4200-b028-11ea-8a27-eb27f9f80051.png)

**Comment by mrin9** [comment] 2020-06-17 03:40
`HTTP method` makes sense when they are displayed along with the API path. For a non-technical user this info do not add any value. If yours target audience is  **Technical Users** then use `render-style=view` which displays the `HTTP method along with the API path`

duplicate of #210

**Closed by mrin9** 2020-06-17 03:40 UTC
