### ISSUE TITLE
PHP support for x-codeSamples

### ISSUE THREAD

**Issue by migrivas** [mrin9/RapiDoc#680] opened 2022-03-06 21:52 UTC
Hello,

Would it be possible to include **PHP** on the supported languages for `x-codeSamples` syntax highlighting?

I suppose that RapiDoc is using *Prism* for this. And checking the code, I see that only *javascript, markup (html, svg, xml), bash, css, yaml, go, java, json, bash, python, http, csharp, yaml* are included.

Is there a way to include *Prism* language definitions for PHP easily ?

Thank you ! :)

**Comment by mrin9** [comment] 2022-03-07 02:41
Let me checkout what size difference it makes after including `php`. 
Since RapiDoc is a Web Component we bundle the entire thing in a single package and we are little sensitive to our bundle size

**Comment by mrin9** [comment] 2022-03-07 17:35
well I tried to include Prism `php` support, but it breaks our code, I think that was the primary reason for us not to include it.
Here is the issue thats already opened with them https://github.com/PrismJS/prism/issues/2769 (is the same issue preventing us)

**Comment by migrivas** [comment] 2022-03-07 18:08
> well I tried to include Prism `php` support, but it breaks our code, I think that was the primary reason for us not to include it. Here is the issue thats already opened with them [PrismJS/prism#2769](https://github.com/PrismJS/prism/issues/2769) (is the same issue preventing us)

Thank you @mrin9 for trying to include *Prism* `php` support again. Let's see if the Prism developers can help to fix the issue.

**Comment by mrin9** [comment] 2022-03-07 20:42
> I'm guessing that docs/prismjs/prism.js is for the website and npm prismjs is for the build, right?

yes docs folder uses the Prism's pre-downloaded code, which we use to build the website and documentation of the product. This works fine and has no connection with npm build. (you may ignore docs folder for this issue)

Our core product is build and bundled using webpack. This is where we get into the issue when we  include `php`

**Comment by RunDevelopment** [comment] 2022-03-07 22:53
> Our core product is build and bundled using webpack.

I see. I have slight problem with the build: `npm run build_windows` doesn't generate `dist/rapidoc.js`. It does generate the minified files, so maybe it's not an issue?

> the issue

What issue specifically? A `Uncaught TypeError: Cannot read property 'tokenizePlaceholders' of undefined`?

Is there an easy way for me to just drop in the generated `dist/rapidoc.js` or `dist/rapidoc-min.js` into some project and see whether PHP highlighting works or not?

**Comment by migrivas** [comment] 2022-03-08 00:51
While RunDevelopment and @mrin9 try to fix this issue... in the meantime I've loaded Prism on my own page and added some dirty javascript/jquery lines that will replace the php `<code>`  tags on the `<rapi-doc>` element.
By the way, the method I use to manipulate the content of `<rapi-doc>`  shadowRoot element may be useful for other things ;)
```HTML
<link href="prism.css" rel="stylesheet" /> <!--generate .css and .js on https://prismjs.com/download.html -->
<rapi-doc id="the-doc" spec-url="openapi.yaml"></rapi-doc> <!-- RapiDoc element -->
<script type="text/javascript" src="jquery.js"></script> <!-- I'm too lazy to use vanilla js all the time -->
<script type="text/javascript">
// Check event RapiDoc is rendered
document.addEventListener('DOMContentLoaded', (event) =>
{
  let docEl = document.getElementById("the-doc");
  docEl.addEventListener('spec-loaded', (e) => { // RapiDoc will fire this event when everything is rendered
    console.log("RapiDoc rendered");
    // load prism.js once RapiDoc is rendered and, once loaded, start replacing the code tags
    loadScript("prism.js", function() {
      // On each tab with data-tab=php0 inside of the RapiDoc shadowRoot code.
      $(".tab-content[data-tab=php0]", $("#the-doc")[0].shadowRoot).each(function () {
        // Get <code> contents, delete html comments, highlight and update
        var phpcontent = $(this).find("code").text();
        phpcontent = phpcontent.replace(/<\!--.*?-->/g, ""); // remove lit html comments
        phpcontent = Prism.highlight(phpcontent, Prism.languages.php, "php");
        $(this).find("code").html(phpcontent);
      });
    });
  });
});
$( document ).ready(function() {
  loadScript('https://unpkg.com/rapidoc/dist/rapidoc-min.js', function()
  {
    console.log("RapiDoc loaded ");
  });
});
// loadScript is just a function to load a script and execute the callback function
var _arr = {};
var _arr 	= {};
function loadScript(scriptName, callback) 
{
  if (!_arr[scriptName]) {
  	_arr[scriptName] = true;
  	var body 		= document.getElementsByTagName('body')[0];
  	var script 		= document.createElement('script');
  	script.type 	= 'text/javascript';
  	script.src 		= scriptName;
  	script.onload = callback;
  	body.appendChild(script);
  } else if (callback) {
  	callback();
  }
}
</script>
```
Thank you guys.

**Comment by mrin9** [comment] 2022-03-31 19:56
closing this as its not a bug on RapiDoc's end.

**Closed by mrin9** 2022-03-31 19:56 UTC
