### ISSUE TITLE
REST methods not in navigation

### ISSUE THREAD

**Issue by ethanabowen** [mrin9/RapiDoc#212] opened 2020-05-13 13:41 UTC
The REST methods (GET/POST/etc) are not displaying in the Read style navigation.

![image](https://user-images.githubusercontent.com/1947151/81819812-6cb63400-94f5-11ea-81ef-3af0fa818ed6.png) (This picture was taken from the RapiDoc website)

The RapiDoc webpage pictures display these values, but no example has a working version of this feature and I was unable to get it working locally.

**Comment by mrin9** [comment] 2020-05-13 16:58
Duplicate of #210

**Closed** 2020-05-27 02:47 UTC
