### ISSUE TITLE
Bearer token

### ISSUE THREAD

**Issue by Chechotkin** [mrin9/RapiDoc#553] opened 2021-09-19 16:35 UTC
Last commit (RapiDoc 9.1.1-beta - WebComponent to View OpenAPI docs), I think, breaks Bearer token. It always empty in request: -H "Authorization: Bearer "

**Comment by mrin9** [comment] 2021-09-19 17:22
It looks like a duplicate of #492 

There has been some recent changes to `9.1.1-beta` to specifically fix this issue which is introduced by release `9.1.0`
However we have now provided a fix in the latest beta so can you once again pickup the latest beta from the dist\rapidoc-min.js  https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js

and give it a try once more ?

also provide your security scheme setup from spec thats causing this issue (something like below)
```yml
  ...
  securitySchemes:
    http-basic:
      type: http
      scheme: basic
    http-bearer:
      type: http
      scheme: bearer
    api_key1:
      type: apiKey
      name: Authorization
      in: header
    api_key2:
      type: apiKey
      name: specialKey
      in: header
    api_key_cookie:
      description: API Key that should be sent in cookie
        authorization filters.
      type: apiKey
      name: api_key_cookie
      in: cookie
```

**Comment by Chechotkin** [comment] 2021-09-19 17:44
When I change this line (which works fine a day ago, but not today)
```
<script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
````
to 
```
<script type="module" src="https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js"></script> 
```
I have error in browser console:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by Chechotkin** [comment] 2021-09-19 17:45
https://unpkg.com/rapidoc@9.0.0/dist/rapidoc-min.js - also works fine for me now

**Comment by mrin9** [comment] 2021-09-19 18:17
> https://unpkg.com/rapidoc@9.0.0/dist/rapidoc-min.js - works fine for me now

This should not work, please check that your cache is cleaned 

to test with latest beta 
do **Not** use the `rapidoc-min.js` from github directly 
```html
<!-- wont work -->
<script type="module" src="https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js"></script> 
```

instead copy `rapidoc-min.js` from github and save it somewhere locally on your server and then refer it from your script tag 
```html
<script type="module" src="local/path/of/rapidoc-min.js"></script> 
<!-- ensure this file takes care of your issues -->
```

**Comment by Chechotkin** [comment] 2021-09-19 18:29
In latest beta Bearer token works as expected

**Closed** 2021-09-19 18:34 UTC
