### ISSUE TITLE
The user is able to execute the request for methods with required path parameters

### ISSUE THREAD

**Issue by mhdsysy** [mrin9/RapiDoc#723] opened 2022-04-14 22:09 UTC
Hi,
As stated in the title, i want to prevent the user from executing requests with path parameters, or required query parameters.
Using swagger without RapiDoc works, and prevents the try button from being executed.

When not providing the parameter, the request gets handled by the resource that returns all of the entities.

![Screenshot 2022-04-15 at 00 06 53](https://user-images.githubusercontent.com/27953412/163484022-dcbb8451-444f-493b-89b1-8456426b79a3.png)

**Comment by mrin9** [comment] 2022-04-15 13:42
duplicate of #701

**Closed** 2022-04-15 13:42 UTC
