### ISSUE TITLE
[9.1.8] URL constructor: undefined is not a valid (unpkg.com)

### ISSUE THREAD

**Issue by samuelcadieux** [mrin9/RapiDoc#672] opened 2022-02-22 19:23 UTC
I noticed an issue with the 9.1.8 released on unpkg where the "Get Token" button no longer issue a request. Looking at the javascript console I noticed the following:
```
Uncaught (in promise) TypeError: URL constructor: undefined is not a valid URL.
    BP https://unpkg.com/rapidoc/dist/rapidoc-min.js:2
    zP https://unpkg.com/rapidoc/dist/rapidoc-min.js:2
    handleEvent https://unpkg.com/rapidoc/dist/rapidoc-min.js:2
    __boundHandleEvent https://unpkg.com/rapidoc/dist/rapidoc-min.js:2
 ```
 
 Switching back to 9.1.4 or using `https://mrin9.github.io/RapiDoc/rapidoc-min.js` fixed the issue.

**Comment by mrin9** [comment] 2022-02-23 00:32
duplicate of https://github.com/mrin9/RapiDoc/issues/667

**Closed by mrin9** 2022-02-23 00:32 UTC
