### ISSUE TITLE
[Bug] Do not appears method page with parameter in path by clicking on it in navbar in focused mode

### ISSUE THREAD

**Issue by aleksandr-bit1** [mrin9/RapiDoc#374] opened 2020-12-03 13:36 UTC
Spec: https://petstore.swagger.io/v2/swagger.json

It happens, for example, when I clicking on "Find pet by ID" in focused mode.
Win 10, chrome 87.0.4280.88.
Screen after click:
![image](https://user-images.githubusercontent.com/75243178/101024306-f5291e80-3584-11eb-9368-fe86c18f9d3f.png)

**Comment by mrin9** [comment] 2020-12-03 14:33
seems like duplicate of #363 . This has been fixed but not yet released.

You can pickup non released build from `dist/rapidoc-min.js` and test it at your end
or give a try to https://mrin9.github.io/RapiDoc/examples/focused-mode.html 

let me know if you still have this issue

**Comment by aleksandr-bit1** [comment] 2020-12-03 17:03
> seems like duplicate of #363

Yes, issue solved. Thank you

**Closed** 2020-12-03 17:55 UTC
