### ISSUE TITLE
Search icon not showing

### ISSUE THREAD

**Issue by JavierPAYTEF** [mrin9/RapiDoc#255] opened 2020-07-01 23:12 UTC
Is there a reason why all the search icons are showing like squares.

![Search](https://user-images.githubusercontent.com/40425968/86299568-fb326200-bbd6-11ea-81ba-f498a9d39caa.png)

**Comment by mrin9** [comment] 2020-07-02 00:57
as stated in the examples did you put `<meta charset="utf-8">` in your html ?


```html
<!doctype html> <!-- Important: must specify -->
<html>
<head>
  <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
  <rapi-doc 
    spec-url = "https://petstore.swagger.io/v2/swagger.json" 
  > </rapi-doc>
</body> 
</html>
```

**Comment by JavierPAYTEF** [comment] 2020-07-02 01:08
I'm getting this from the examples hosted in rapidoc site itself, that's why I find it weird. Firefox and Chrome have the same issue.
Is this a font that's supposed to be installed in the system?
In chrome it's loading the font as Arial, but Firefox loads Open Sans and it's still not displaying.

https://mrin9.github.io/RapiDoc/examples/example1.html

![page](https://user-images.githubusercontent.com/40425968/86305037-08efe380-bbe7-11ea-9745-3a11b2a22166.png)

**Comment by mrin9** [comment] 2020-07-02 01:14
can you visit any other site which shows unicode characters such as https://en.wikipedia.org/wiki/List_of_Unicode_characters#Arrows

this will isolate is the issue is due to OS/Browser or RapiDoc

**Comment by JavierPAYTEF** [comment] 2020-07-02 01:27
Wikipedia page loads ok, but from looking at the styles, it's using a custom font. So that's probably why it's working. Here is a screenshot of how that looks:
In case it helps, I'm using windows 7 to test this.
In firefox where it loads Open Sans you can see all the font information, but it's still not loading for some reason, even using Open Sans. The second screenshot shows the information.

![page](https://user-images.githubusercontent.com/40425968/86306029-903e5680-bbe9-11ea-9066-723193ec43bd.png)



![page2](https://user-images.githubusercontent.com/40425968/86306040-95030a80-bbe9-11ea-8272-7230d0ac23b1.png)

**Comment by JavierPAYTEF** [comment] 2020-07-02 01:33
I missed your comment about the fonts from google, they appear to be downloading fine, which is weird.
Is there a way to change these icons?

![page3](https://user-images.githubusercontent.com/40425968/86306468-b9131b80-bbea-11ea-9fed-f68ac2b8a48d.png)

**Comment by mrin9** [comment] 2020-07-02 01:39
>Is there a way to change these icons?

these are the part of font, windows 7 may not be able to display all the utf-8 charset even if they are provided by the font.
But to answer your question yes you can change the font that works for you. As long as you can get that font to display the unicode chars
The example above shows how you can provide your own font and the place where to download it from

**Comment by mrin9** [comment] 2020-07-03 04:30
I am guessing this is a browser/os issue I wont be able to help much as I or any of the team members are able to recreate this issue on  our end.
But if you are able to crack it down, do let us know how ? may help someone else.

closing it

**Closed by mrin9** 2020-07-03 04:30 UTC
