### ISSUE TITLE
Lock icon styling

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#654] opened 2022-02-07 19:38 UTC
The right panel shows lock icon. Is it possible to change color of icon to say green, when an api key is added?

**Comment by mrin9** [comment] 2022-02-22 00:57
duplicate of #645 

An API can have complex API-key requirements , it may 
- need just one key
- or multiple keys
- mix of keys evaluated using AND / OR  

Therefore we suggest you to check at the bottom of the request which exactly states how many keys are applied. A green color wont be able to convey this properly 

![image](https://user-images.githubusercontent.com/5056899/151353119-e35f4e34-f9c1-4f92-9445-35cc205429fa.png)

**Closed by mrin9** 2022-02-22 00:57 UTC
