### ISSUE TITLE
Discriminator does not switch Schema

### ISSUE THREAD

**Issue by YousefHaggy** [mrin9/RapiDoc#1057] opened 2024-11-14 14:39 UTC
There's a similar issue in Swagger
https://github.com/swagger-api/swagger-ui/issues/2438

When using allOf with discriminator for inheritance, RapiDoc just displays the base parent Schema with no notion of the children schema.

ReDoc supports this case, they have a drop down to select the discriminator value and render the matching child Schema

Example: https://github.com/Rebilly/ReDoc/blob/main/docs%2Fimages%2Fdiscriminator-demo.gif

**Comment by mrin9** [comment] 2024-11-14 19:04
Duplicate of #170

**Closed as completed by mrin9** 2024-11-14 19:04 UTC
