### ISSUE TITLE
Missing HTTP headers in response tab

### ISSUE THREAD

**Issue by ubiqel** [mrin9/RapiDoc#587] opened 2021-10-17 08:20 UTC
Hi, thanks for making RapiDoc. I really like it. Recently I found an issue in "Reponse Headers" tab: only some of http headers from the response are shown. You can see it in your own example of a [method to get a pet by id](https://mrin9.github.io/RapiDoc/examples/petstore-extended.html#get-/pet/-petId-)(or any other). In response tab:
```http
content-type: application/json
```

But if you make the same request with curl, you will see:
```http
date: Sun, 17 Oct 2021 08:11:23 GMT
content-type: application/json
access-control-allow-origin: *
access-control-allow-methods: GET, POST, DELETE, PUT
access-control-allow-headers: Content-Type, api_key, Authorization
server: Jetty(9.2.9.v20150224)
```

**Comment by mrin9** [comment] 2021-10-17 19:48
seems like a duplicate of #288

**Closed as completed by mrin9** 2021-10-17 19:48 UTC
